better issue getting

diff --git a/.github/workflows/update-version-label.yml b/.github/workflows/update-version-label.yml
--- a/.github/workflows/update-version-label.yml
+++ b/.github/workflows/update-version-label.yml
@@ -17,7 +17,12 @@ jobs:
       - name: Get associated Linear issue ID
         run: |
           issue_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments | jq -r '.[] | select(.user.login == "linear[bot]") | .body' | grep -oP 'ACK-\d+')
-          echo "issue_id=$issue_id" >> $GITHUB_ENV
+          if [[ ! -z "$issue_id" ]]; then
+            echo "issue_id=$issue_id" >> $GITHUB_ENV
+          else
+            echo "Error: Issue ID not found."
+            exit 1
+          fi
 
       - name: Set issue labels
         run: |
